cli:
  providers:
    default: ansible
help:
  max_content_width: 200
logging:
  maxBytes: 10000000
  backupCount: 5
  debug: False
  verbose: 0
  log_file:
bastion_mode:
  config_file: sftp-config.json
  enabled: True
  keep_alive: True
  poll_wait_time: 5
  sftp_sync: True
