---
- hosts: local
  vars:
    help:
      readme: |
        Task Runner for the Task Runner!
      examples:
    inventory: |
      [local]
      localhost      
    required_parameters:
    optional_parameters:
      -b: build
      --s: setup_and_test
      --u: uninstall      
      -bp|--build-and-push: deployment_host_and_path
    functions:
      setup_and_test:
        shell: bash
        source: |-
          python setup.py -q install
          tasks run --help
      uninstall:
        shell: bash
        source: |-
          pip uninstall ansible_taskrunner -y        
      build:
        shell: bash
        source: |-
          set -o errexit
          for pyver in py2 py3;do
            if ! test -d lib/${pyver};then 
              mkdir lib/${pyver}
              source activate $pyver
              pip install -t lib/${pyver} -r requirments
            fi
          done
          __version=$(egrep '.*__version__ =' tasks.py | cut -d\  -f3 | tr -d "'")
          echo "Version is ${__version}"
          __release_dir=release/${__version}
          lint_result=$(./tasks.py --help)
          echo "Initial lint OK, proceeding with build"
          if [[ "$OSTYPE" =~ .*msys.* ]];then 
            echo "OSType is Windows, nesting libdir ..."
            mkdir windows
            cp -r lib plugins windows
            echo "Creating zip-app"
            make-zipapp -f tasks.py -X __pycache__ -x .pyc -d windows
            if test -d windows;then rm -rf windows;fi
          else
            echo "OSType is most likely POSIX native"
            echo "Creating zip-app"
            ../make-zipapp/make-zipapp.py -f tasks.py -d lib
          fi
          lint_result=$(./tasks.py --help)
          echo "Initial lint OK, proceeding with release"
          if ! test -d ${__release_dir};then mkdir -p ${__release_dir};fi
          mv -f tasks ${__release_dir}
          echo "Replacing current executable: $(which tasks)"
          yes | cp ${__release_dir}/tasks $(which tasks)
          if [[ -n $deployment_host_and_path ]];then
            echo "Pushing up"
            scp_result=$(scp ${__release_dir}/tasks ${deployment_host_and_path})
          fi
  tasks:
    - debug: 
        msg: Done!
...